config/routes.rb
Rails.application.routes.draw do

  root   'recipes#home'
  get    'nav_search' => 'recipes#nav_search'
  get    'course'     => 'recipes#course'
  get    'about'      => 'recipes#about'
  get    'login' 		  => 'sessions#new'
  post   'login' 		  => 'sessions#create'
  delete 'logout'		  => 'sessions#destroy'

  resources :recipes
  resources :users

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base


	validates :title, presence: true, uniqueness: true

	def self.search(query)
		where("title like ?", "%#{query}%")
	end
	
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50, minimum: 3 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false } 
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def User.digest(string)
  	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
  	BCrypt::Password.create(string,cost: cost)
  end

  def User.new_token
  	SecureRandom.urlsafe_base64
  end

  def remember
  	self.remember_token = User.new_token
  	update_attribute(:remember_token, User.digest(remember_token))
  end

  def forget
  	update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
  	return false if remember_digest.nil?
  	BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def home
  end

  def about
  end

	def nav_search
		if !params[:query].present?
			redirect_to :back
		else
			@recipes = Recipe.search(params[:query])
			if !@recipes.present?
				flash[:warning] = "#{params[:query]} not found!"
				redirect_to :back
			else
				render "index"
			end
		end
	end

	def index
		@recipes = Recipe.all
	end

	def create
		@recipe = Recipe.new(recipe_params)

		if @recipe.save
			redirect_to @recipe
		else
			flash[:warning] = "Recipe save failed"
			redirect_to new_recipe_path
		end
	end

	def new
		@recipe = Recipe.new
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])
		if @recipe.update(recipe_params)
			redirect_to recipe_path
		else
			render 'edit'
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy
		flash[:success] = "#{@recipe.title} - was deleted successfully"
		redirect_to recipes_path	# back to the list

	end

	def course
		@recipes = Recipe.where("course = ?", params[:course])
		#render plain: @recipes
		unless !@recipes.blank?
			flash[:warning] = "No #{params[:course]} recipes found"
			redirect_to root_path
		end
	end

	private
	def recipe_params
		params.require(:recipe).permit(:title, :course, :main_ingredient, :source, :description, :ingredients, :directions, :prep_time, :cook_time, :total_time, :servings)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		#log the user in and redirect to recipe index
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to recipes_path
  	else
  		# Display error message and route to 'new user page'
  		flash.now[:danger] = "Invalid email/password combination"
  		redirect_to root_path
   	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
  		flash[:success] = "User created successfylly."
  		redirect_to @user
  	else
  		render 'new'
  	end

  end


  private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user_id
			end
		end
	end

	def logged_in?
		!current_user.nil?
	end

	# Removes the persistent session
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	# Logs out the current_user
	def log_out
		forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user.
	def gravatar_for(user)
		gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Your Recipe List
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", 		about_path %></li>
			<li><%= link_to "Contact",  "#"%><li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
	<div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Recipes', root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <% if logged_in? %>
              <li><%= link_to 'Enter', new_recipe_path %></li>
              <li><%= link_to 'List', recipes_path %></li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Profile', current_user %></li>
                  <li><%= link_to 'Settings', '#' %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Log out', logout_path, method: "delete" %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Log-in', login_path %></li>
            <% end %>
          </ul>

          <form action="nav_search" class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Title Search..." name="query">
            </div>
            <button type="Submit" class="btn btn-primary">Go</button>
          </form>
        </div><!--/.nav-collapse -->
      </div><!--/.container-fluid -->
    </nav>

    <!-- Flash Messages -->
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
    <% end %>
  </div> <!-- container -->
  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe Filer</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<h3>This is something about us</h3>

app/views/pages/home.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="jumbotron">
		<h1>Recipes Directory</h1>
		<p>All types of recipes for all types of occasions.</p>
		</div>
	</div>
</div>

app/views/recipes/_form.html.erb
			<%= form_for @recipe do |f| %>
				<div class="form-group">
					<%= f.text_field :title, placeholder: 'Recipe Title', class: 'form-control' %>
					<%= f.text_field :description, placeholder: 'Describe the recipe', class: 'form-control' %>
				</div>
				<div class='form-group'>
					<div class="input-group">
						<div class="input-group-addon">Course</div>
						<%= f.select :course, options_for_select(['Main', 'Appetizer', 'Side', 'Dessert', 'Sauce', 'Component']), {}, {	class: 'form-control'} %>
					</div>
				</div>
				<div class="form-group">
					<%= f.text_field :main_ingredient, placeholder: 'Main Ingredient', class: 'form-control' %>
					<%= f.text_area :ingredients, placeholder: 'Ingredient List', class: 'form-control' %>
					<%= f.text_area :directions, placeholder: 'Directions', class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.label "Recipe Times" %>
					<div class="input-group">
						<div class="col-md-4">
							<%= f.text_field :prep_time, placeholder: 'prep time', class: 'form-control' %>
						</div>
						<div class="col-md-4">
							<%= f.text_field :cook_time, placeholder: 'cooking time', class: 'form-control' %>
						</div>
						<div class="col-md-4">
							<%= f.text_field :total_time, placeholder: 'total time', class: 'form-control' %>
						</div>
					</div>
				</div>
				<div class="form-group">
					<%= f.text_field :servings, placeholder: 'Number of servings', class: 'form-control' %>
					<%= f.url_field :source, placeholder: 'Source of this recipe', class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.submit 'Save', class: 'btn btn-success'%>
				</div>
			
			<% end %>

app/views/recipes/about.html.erb
<h1>About</h1>
<p>This application will hold all my recipes and willb e accessible via desktop and mobile.</p>

app/views/recipes/course.html.erb
<h1>All recipes for <strong><%= "#{params[:course]}" %>s</strong></h1>
<table class='table table-striped table-condensed'>
	<tr>
		<th>Title</th>
		<th>Course</th>
		<th>Main Ingredient</th>
		<th colspan="2">Actions</th>
	</tr>
	<% @recipes.each do |r| %>
	<tr>
		<td><%= link_to r.title, recipe_path(r.id) %></td>
		<td><%= r.course %></td>
		<td><%= r.main_ingredient %></td>
		<td><%= link_to "Edit", edit_recipe_path(r.id) %></td>
		<td><%= link_to "Delete", recipe_path(r.id), :method => :delete, :confirm => "Are you sure ?"%></td>
	</tr>
</table>
	<% end %>

app/views/recipes/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
		<div class="well">
			<h1>Edit Recipe</h1>

			<%= render partial: "form" %>

		</div>
	</div>
</div>

app/views/recipes/home.html.erb
<div class="jumbotron">
	<h1><%= icon('cutlery') %> Your Recipes</h1>
	<p>Everything in one place everywhere.</p>
</div>
<div class="row home_menu">
	<div class="col-md-4 col-sm-6" id="Main">
		<%= link_to image_tag("Main", class: "img-responsive") + '<span class="glyphicon glyphicon-fire"></span>'.html_safe + " Main Dish Recipes", controller: "recipes", action: "course", course: "Main" %>
	</div>
	<div class="col-md-4 col-sm-6" id="Appetizer">
		<%= link_to image_tag("Appetizer", class: "img-responsive") + "Appetizer Recipes", controller: "recipes", action: "course", course: "Appetizer" %>
	</div>
	<div class="col-md-4 col-sm-6" id="Side">
		<%= link_to image_tag("Side", class: "img-responsive") + '<span class="glyphicon glyphicon-hand-right"></span>'.html_safe  + " Side Dish Recipes", controller: "recipes", action: "course", course: "Side" %>
	</div>
	<div class="col-md-4 col-sm-6" id="Dessert">
		<%= link_to image_tag("Dessert", class: "img-responsive") + '<span class="glyphicon glyphicon-ice-lolly-tasted"></span>'.html_safe + " Dessert Recipes", controller: "recipes", action: "course", course: "Dessert" %>
	</div>
	<div class="col-md-4 col-sm-6" id="Sauce">
		<%= link_to image_tag("Sauce", class: "img-responsive") + "Sauce Recipes", controller: "recipes", action: "course", course: "Sauce" %>
	</div>
	<div class="col-md-4 col-sm-6" id="Component">
		<%= link_to image_tag("Component", class: "img-responsive") + '<span class="glyphicon glyphicon-leaf"></span>'.html_safe  + " Component Recipes", controller: "recipes", action: "course", course: "Component" %>
	</div>
</div>

app/views/recipes/index.html.erb
<div class="row">		
	<div class="col-md-8 col-md-offset-1">
		<h1>Recipe List</h1>
		<table class="table table-striped table-condensed">
			<tr>
				<th>Title</th>
				<th colspan="2">Actions</th>
				<th>Course</th>
				<th>Main Ingredient</th>
			</tr>
			<% @recipes.each do |r| %>
				<tr>
					<td><%= link_to r.title, recipe_path(r.id), class: "btn btn-default btn-xs btn-block" %></td>
					<td><%= link_to "Edit", edit_recipe_path(r.id) %></td>
					<td>
						<%= link_to recipe_path(r.id), :class => "btn btn-primary btn-xs", :method => :delete, data: { :confirm => "Are you sure?" } do %>
							<span class="glyphicon glyphicon-trash"></span>
						<% end %>
					</td>
					<td><%= r.course %></td>
					<td><%= r.main_ingredient %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/recipes/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="well">
			<h1>New Recipe Entry</h1>

			<%= form_for :recipe, url: recipes_path do |f| %>
				<div class="form-group">
					<%= f.text_field :title, placeholder: 'Recipe Title', class: 'form-control' %>
					<%= f.text_field :description, placeholder: 'Describe the recipe', class: 'form-control' %>
				</div>
				<div class='form-group'>
					<div class="input-group">
						<div class="input-group-addon">Course</div>
						<%= f.select :course, options_for_select(['Main', 'Appetizer', 'Side', 'Dessert', 'Sauce', 'Component']), {}, {	class: 'form-control'} %>
					</div>
				</div>
				<div class="form-group">
					<%= f.text_field :main_ingredient, placeholder: 'Main Ingredient', class: 'form-control' %>
					<%= f.text_area :ingredients, placeholder: 'Ingredient List', class: 'form-control' %>
					<%= f.text_area :directions, placeholder: 'Directions', class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.label "Recipe Times" %>
					<div class="input-group">
						<div class="col-md-4">
							<%= f.text_field :prep_time, placeholder: 'prep time', class: 'form-control' %>
						</div>
						<div class="col-md-4">
							<%= f.text_field :cook_time, placeholder: 'cooking time', class: 'form-control' %>
						</div>
						<div class="col-md-4">
							<%= f.text_field :total_time, placeholder: 'total time', class: 'form-control' %>
						</div>
					</div>
				</div>
				<div class="form-group">
					<%= f.text_field :servings, placeholder: 'Number of servings', class: 'form-control' %>
					<%= f.url_field :source, placeholder: 'Source of this recipe', class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.submit 'Save', class: 'form-control btn-success'%>
				</div>
			
			<% end %>
		</div>
	</div>
</div>

app/views/recipes/show.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<h1><%= @recipe.title %></h1>
		<p><%= @recipe.description %></p>
		<h3>Ingredients</h3>
		<pre><%= @recipe.ingredients %></pre>

		<h3>Directions</h3>
		<pre><%= @recipe.directions %></pre>
	</div>
</div>

app/views/recipes/update.html.erb
<h1>recipes#update</h1>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation" %>
		<div class = "alert alert-danger" %>
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h1>Signup</h1>
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			<%= f.label 		     :name %>
			<%= f.text_field     :name, class: "form-control"%>

			<%= f.label          :email %>
			<%= f.email_field    :email, class: "form-control" %>

			<%= f.label          :password %>
			<%= f.password_field :password, class: "form-control" %>

			<%= f.label          :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: "form-control" %>

			<%= f.submit "Create my account", class: "btn btn-primary" %>

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h1>
	<%= gravatar_for @user %>
	<%= @user.name %>
</h1>